(()=>{
const DB='cadence-v3',STORE='media',PK='cadencePackagePending';
const $=s=>document.querySelector(s);
const status=t=>{const e=$('#status');if(e)e.textContent=t};
const openDB=()=>new Promise((r,j)=>{const x=indexedDB.open(DB,1);x.onsuccess=()=>r(x.result);x.onerror=()=>j(x.error)});
const allMedia=async()=>{const d=await openDB();return new Promise((r,j)=>{const x=d.transaction(STORE,'readonly').objectStore(STORE).getAll();x.onsuccess=()=>r(x.result||[]);x.onerror=()=>j(x.error)})};
const putMedia=async o=>{const d=await openDB();return new Promise((r,j)=>{const x=d.transaction(STORE,'readwrite').objectStore(STORE).put(o);x.onsuccess=()=>r();x.onerror=()=>j(x.error)})};
const clearMedia=async()=>{const d=await openDB();return new Promise((r,j)=>{const x=d.transaction(STORE,'readwrite').clear();x.onsuccess=()=>r();x.onerror=()=>j(x.error)})};
const blobToData=blob=>new Promise((r,j)=>{const f=new FileReader();f.onload=()=>r(f.result);f.onerror=()=>j(f.error);f.readAsDataURL(blob)});
const dataToBlob=data=>{const [head,b64]=data.split(',');const bin=atob(b64),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return new Blob([u],{type:(head.match(/data:([^;]+)/)||[])[1]||'application/octet-stream'})};
function studioState(){return{savedAt:new Date().toISOString(),hue:Number($('#hue')?.value||290),repeat:$('#repeat')?.textContent.includes('ON')||false,cross:Number($('#cross')?.value||0),master:Number($('#master')?.value||.9),eq:{low:Number($('#low')?.value||0),mid:Number($('#mid')?.value||0),high:Number($('#high')?.value||0)},decks:{A:{id:window.CadenceRuntime?.getDeck?.('A')?.id||null,volume:Number($('#volA')?.value||1),pitch:Number($('#pitchA')?.value||0)},B:{id:window.CadenceRuntime?.getDeck?.('B')?.id||null,volume:Number($('#volB')?.value||1),pitch:Number($('#pitchB')?.value||0)}},timeline:window.CadenceTimeline?.getState?.()||null};}
async function exportPackage(){try{const media=await allMedia();status('Packaging project…');const files=[];for(const m of media)files.push({id:m.id,name:m.name,size:m.size,type:m.type,kind:m.kind,data:await blobToData(m.blob)});const pkg={format:'cadence-project',version:1,createdAt:new Date().toISOString(),studio:studioState(),media:files};const blob=new Blob([JSON.stringify(pkg)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='cadence-project.cadence.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);status(`Project package exported · ${media.length} media file(s)`)}catch(e){console.error(e);status('Package export failed.');alert('Cadence package export failed: '+(e?.message||e))}}
async function importPackage(file){try{status('Importing project package…');const pkg=JSON.parse(await file.text());if(pkg.format!=='cadence-project')throw new Error('Not a Cadence project package');if(!Array.isArray(pkg.media))throw new Error('Package contains no media');await clearMedia();for(const m of pkg.media)await putMedia({id:m.id,name:m.name,size:m.size,type:m.type,kind:m.kind,blob:dataToBlob(m.data)});if(pkg.studio?.timeline&&window.CadenceTimeline?.setState)window.CadenceTimeline.setState(pkg.studio.timeline);localStorage.setItem(PK,JSON.stringify(pkg.studio||{}));status(`Imported ${pkg.media.length} media file(s) · reloading…`);setTimeout(()=>location.reload(),350)}catch(e){console.error(e);status('Package import failed.');alert('Cadence package import failed: '+(e?.message||e))}}
$('#exportPackage')?.addEventListener('click',exportPackage);
$('#importPackage')?.addEventListener('click',()=>{const i=document.createElement('input');i.type='file';i.accept='.cadence.json,application/json';i.onchange=()=>i.files[0]&&importPackage(i.files[0]);i.click()});
})();