(()=>{
var $=function(s){return document.querySelector(s)},stage=$('#stage'),viz=$('#viz'),ctx=viz.getContext('2d'),video=$('#video'),image=$('#image'),file=$('#files'),list=$('#mediaList'),status=$('#status');
var items=[],active=null,AC=null,master=null,analyser=null,dest=null,hue=290,visualMode='bars',repeat=false,recording=null,chunks=[];
var decks={A:{el:$('#audioA'),item:null,cue:0,loop:false,gain:null,low:null,mid:null,high:null,xf:1},B:{el:$('#audioB'),item:null,cue:0,loop:false,gain:null,low:null,mid:null,high:null,xf:1}};
var dbp=new Promise(function(ok,bad){var r=indexedDB.open('cadence-v3',1);r.onupgradeneeded=function(){if(!r.result.objectStoreNames.contains('media'))r.result.createObjectStore('media',{keyPath:'id'})};r.onsuccess=function(){ok(r.result)};r.onerror=function(){bad(r.error)}});
function all(){return dbp.then(function(d){return new Promise(function(ok,bad){var q=d.transaction('media','readonly').objectStore('media').getAll();q.onsuccess=function(){ok(q.result||[])};q.onerror=function(){bad(q.error)}})})}
function put(o){return dbp.then(function(d){return new Promise(function(ok,bad){var q=d.transaction('media','readwrite').objectStore('media').put(o);q.onsuccess=function(){ok()};q.onerror=function(){bad(q.error)}})})}
function del(id){return dbp.then(function(d){return new Promise(function(ok,bad){var q=d.transaction('media','readwrite').objectStore('media').delete(id);q.onsuccess=function(){ok()};q.onerror=function(){bad(q.error)}})})}
function say(t){if(status)status.textContent=t} function fmt(v){return isFinite(v)?Math.floor(v/60)+':'+String(Math.floor(v%60)).padStart(2,'0'):'0:00'}
function init(){if(AC)return;AC=new (window.AudioContext||window.webkitAudioContext)();master=AC.createGain();analyser=AC.createAnalyser();analyser.fftSize=1024;dest=AC.createMediaStreamDestination();master.connect(analyser);analyser.connect(AC.destination);analyser.connect(dest);Object.keys(decks).forEach(function(k){var d=decks[k];d.source=AC.createMediaElementSource(d.el);d.low=AC.createBiquadFilter();d.mid=AC.createBiquadFilter();d.high=AC.createBiquadFilter();d.gain=AC.createGain();d.low.type='lowshelf';d.low.frequency.value=160;d.mid.type='peaking';d.mid.frequency.value=1000;d.high.type='highshelf';d.high.frequency.value=5000;d.source.connect(d.low);d.low.connect(d.mid);d.mid.connect(d.high);d.high.connect(d.gain);d.gain.connect(master);d.gain.gain.value=Number($('#vol'+k).value||1)});window.CadenceRuntime={ensure:init,context:function(){return AC},master:function(){return master},analyser:function(){return analyser},destination:function(){return dest},getDeck:function(k){return {id:decks[k].item?decks[k].item.id:null,volume:Number($('#vol'+k).value),pitch:Number($('#pitch'+k).value),cue:decks[k].cue,loop:decks[k].loop}},getMix:function(){return {master:Number($('#master').value),cross:Number($('#cross').value),low:Number($('#low').value),mid:Number($('#mid').value),high:Number($('#high').value)}},loadDeck:loadDeck}}
function clearStage(){video.pause();video.removeAttribute('src');image.removeAttribute('src');video.style.display='none';image.style.display='none';$('#empty').style.display='grid'}
function loadDeck(k,item){if(!item)return;init();var d=decks[k];d.el.pause();if(d.url)URL.revokeObjectURL(d.url);d.url=URL.createObjectURL(item.blob);d.item=item;d.cue=0;d.el.src=d.url;d.el.load();$('#name'+k).textContent=item.name;clearStage();if(item.kind==='video'){video.src=d.url;video.style.display='block';video.muted=true;video.load();$('#empty').style.display='none'}else if(item.kind==='image'){image.src=d.url;image.style.display='block';$('#empty').style.display='none'}else $('#empty').style.display='none';if(window.CadenceBeatGrid&&window.CadenceBeatGrid.refresh)window.CadenceBeatGrid.refresh();sync();say('Loaded '+item.name+' to Deck '+k)}
function sync(){$('#cueReadA').textContent=fmt(decks.A.cue);$('#cueReadB').textContent=fmt(decks.B.cue);$('#loopRead').textContent=decks.A.loop||decks.B.loop?'ON':'OFF'}
function render(){list.innerHTML=items.map(function(o){return '<button class="mediaItem'+(active&&active.id===o.id?' active':'')+'" data-id="'+o.id+'"><b>'+o.name.replace(/[<>]/g,'')+'</b><div class="tag">'+o.kind+' · '+Math.round(o.size/1024)+' KB</div></button>'}).join('');list.querySelectorAll('.mediaItem').forEach(function(b){b.onclick=function(){active=items.find(function(x){return x.id===b.dataset.id});render();loadDeck('A',active)}})}
file.onchange=async function(){for(var f of Array.from(file.files)){var kind=f.type.indexOf('video/')===0?'video':f.type.indexOf('image/')===0?'image':'audio';var o={id:crypto.randomUUID(),name:f.name,size:f.size,type:f.type,kind:kind,blob:f};items.push(o);await put(o)}render();if(!active&&items[0]){active=items[0];loadDeck('A',active)}say('Media saved locally.');file.value=''};
function wire(k){var d=decks[k];$('#play'+k).onclick=async function(){init();await AC.resume();if(d.el.paused){await d.el.play();$('#play'+k).textContent='⏸'}else{d.el.pause();$('#play'+k).textContent='▶'}};$('#cue'+k).onclick=function(){d.el.currentTime=d.cue||0;d.el.pause()};$('#setCue'+k).onclick=function(){d.cue=d.el.currentTime;sync()};$('#loop'+k).onclick=function(){d.loop=!d.loop;d.el.loop=d.loop;$('#loop'+k).textContent=d.loop?'LOOP ON':'LOOP';sync()};$('#vol'+k).oninput=function(e){if(d.gain)d.gain.gain.value=Number(e.target.value)*d.xf};$('#pitch'+k).oninput=function(e){d.el.playbackRate=1+Number(e.target.value)/100};d.el.onloadedmetadata=function(){$('#dur'+k).textContent=fmt(d.el.duration)};d.el.ontimeupdate=function(){$('#time'+k).textContent=fmt(d.el.currentTime);var p=$('#wave'+k+' .playhead');if(p&&d.el.duration)p.style.left=(d.el.currentTime/d.el.duration*100)+'%'}}wire('A');wire('B');
function applyCross(x){var a=Math.cos((x+1)*Math.PI/4),b=Math.cos((1-x)*Math.PI/4);decks.A.xf=a;decks.B.xf=b;['A','B'].forEach(function(k){var d=decks[k],v=Number($('#vol'+k).value||1);if(d.gain)d.gain.gain.value=v*d.xf})}
$('#loadA').onclick=function(){if(active)loadDeck('A',active)};$('#loadB').onclick=function(){if(active)loadDeck('B',active)};$('#master').oninput=function(e){init();master.gain.value=Number(e.target.value)};$('#cross').oninput=function(e){init();applyCross(Number(e.target.value))};$('#low').oninput=function(e){Object.keys(decks).forEach(function(k){if(decks[k].low)decks[k].low.gain.value=Number(e.target.value)*12})};$('#mid').oninput=function(e){Object.keys(decks).forEach(function(k){if(decks[k].mid)decks[k].mid.gain.value=Number(e.target.value)*10})};$('#high').oninput=function(e){Object.keys(decks).forEach(function(k){if(decks[k].high)decks[k].high.gain.value=Number(e.target.value)*12})};
$('#sync').onclick=function(){var a=window.CadenceBPM&&window.CadenceBPM.get('A'),b=window.CadenceBPM&&window.CadenceBPM.get('B');if(!a||!b)return say('Load both decks and wait for BPM analysis.');decks.B.el.playbackRate=Math.max(.5,Math.min(1.5,a/b));say('Beat matched B to A. '+b+' → '+a+' BPM')};$('#visual').onclick=function(){stage.classList.add('visualOnly')};$('#combo').onclick=function(){stage.classList.remove('visualOnly')};$('#hue').oninput=function(e){hue=Number(e.target.value)};$('#shuffle').onclick=function(){if(!items.length)return say('Add media first.');active=items[Math.floor(Math.random()*items.length)];render();loadDeck('A',active)};$('#repeat').onclick=function(){repeat=!repeat;$('#repeat').textContent='🔁 REPEAT: '+(repeat?'ON':'OFF')};$('#full').onclick=async function(){try{if(!document.fullscreenElement)await stage.requestFullscreen();else await document.exitFullscreen()}catch(e){stage.classList.toggle('forceFull')}};$('#clear').onclick=async function(){for(var o of items)await del(o.id);items=[];active=null;render();clearStage();say('Local library cleared.')};$('#timeline').oninput=function(e){if(decks.A.el.duration)decks.A.el.currentTime=Number(e.target.value)/1000*decks.A.el.duration};
$('#saveProject').onclick=function(){var p={version:5,settings:{hue:hue,repeat:repeat,master:Number($('#master').value),cross:Number($('#cross').value),eq:{low:Number($('#low').value),mid:Number($('#mid').value),high:Number($('#high').value)}},decks:{A:{id:decks.A.item&&decks.A.item.id,cue:decks.A.cue,loop:decks.A.loop},B:{id:decks.B.item&&decks.B.item.id,cue:decks.B.cue,loop:decks.B.loop}},timeline:window.CadenceTimeline&&window.CadenceTimeline.getState?window.CadenceTimeline.getState():null};var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}));a.download='cadence-project.json';a.click()};
$('#record').onclick=function(){init();if(recording){recording.stop();return}try{var stream=viz.captureStream(30);dest.stream.getAudioTracks().forEach(function(t){stream.addTrack(t)});var mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm';recording=new MediaRecorder(stream,{mimeType:mime});chunks=[];recording.ondataavailable=function(e){if(e.data.size)chunks.push(e.data)};recording.onstop=function(){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:mime}));a.download='cadence-mix.webm';a.click();recording=null;$('#record').textContent='⏺ RECORD'};recording.start(250);$('#record').textContent='⏹ STOP'}catch(e){say('Recording unavailable.')}};
$('#visualMode')&&$('#visualMode').addEventListener('change',function(e){visualMode=e.target.value});$('#randomVisual')&&$('#randomVisual').addEventListener('click',function(){var m=['bars','wave','rings','particles','tunnel'];visualMode=m[Math.floor(Math.random()*m.length)];$('#visualMode').value=visualMode});
function draw(){requestAnimationFrame(draw);var w=viz.clientWidth,h=viz.clientHeight;if(!w||!h||!analyser)return;var d=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(d);ctx.clearRect(0,0,w,h);var react=Number($('#visualReact')&&$('#visualReact').value||1),dim=Number($('#visualDim')&&$('#visualDim').value||.28);ctx.globalAlpha=Math.max(.05,1-dim);var t=performance.now()*.001;
if(visualMode==='wave'){ctx.beginPath();for(var x=0;x<w;x++){var v=d[Math.floor(x/w*d.length)]/255,y=h/2+Math.sin(x*.025+t*2)*v*h*.4*react;if(x)ctx.lineTo(x,y);else ctx.moveTo(x,y)}ctx.strokeStyle='hsl('+hue+' 90% 65%)';ctx.lineWidth=2;ctx.stroke()}
else if(visualMode==='rings'){for(var i=0;i<32;i++){ctx.beginPath();ctx.arc(w/2,h/2,20+i*10+(d[i*3]||0)*.3*react,0,Math.PI*2);ctx.strokeStyle='hsl('+((hue+i*9)%360)+' 90% 65%)';ctx.stroke()}}
else if(visualMode==='particles'){for(var p=0;p<140;p++){var q=d[p%d.length]/255*react,ang=p*2.399+t*(.3+q),rad=20+(p*7%Math.min(w,h)/2)+q*90;var px=w/2+Math.cos(ang)*rad,py=h/2+Math.sin(ang)*rad;ctx.fillStyle='hsl('+((hue+p*3)%360)+' 90% 65%)';ctx.fillRect(px,py,1+q*4,1+q*4)}}
else if(visualMode==='tunnel'){var base=Math.min(w,h)*.08;for(var z=0;z<24;z++){var pulse=(d[(z*7)%d.length]||0)/255*react,scale=(z+1)/24,ww=base+scale*w*.55+pulse*80;ctx.strokeStyle='hsl('+((hue+z*12)%360)+' 90% 60%)';ctx.strokeRect(w/2-ww/2+Math.sin(t+z)*10,h/2-ww*.3,ww,ww*.6)}}
else{var bw=w/d.length;for(var j=0;j<d.length;j++){var vv=d[j]/255*react;ctx.fillStyle='hsl('+((hue+j*1.4)%360)+' 90% 60%)';ctx.fillRect(j*bw,h-Math.max(2,vv*h*.8),Math.max(1,bw-1),Math.max(2,vv*h*.8))}}ctx.globalAlpha=1}
all().then(function(x){items=x;render();say(x.length?x.length+' local file(s) ready.':'Ready — add media.')});draw();
})();