(()=>{
const audioA=document.querySelector('#audioA'),audioB=document.querySelector('#audioB'),sync=document.querySelector('#sync');
if(!audioA||!audioB)return;
const cache=new Map(),bps={A:null,B:null};
function addReadout(audio,k){const row=audio.closest('.deck')?.querySelector('.time');if(!row||row.querySelector(`[data-bpm="${k}"]`))return;const s=document.createElement('span');s.dataset.bpm=k;s.textContent='BPM —';s.style.margin='0 auto';s.style.color='#aaa';s.style.fontFamily='ui-monospace,monospace';s.style.fontSize='11px';row.insertBefore(s,row.lastElementChild)}
addReadout(audioA,'A');addReadout(audioB,'B');
function setReadout(k,bpm){const el=document.querySelector(`[data-bpm="${k}"]`);if(el)el.textContent=bpm?`BPM ${bpm.toFixed(1).replace(/\.0$/,'')}`:'BPM —'}
async function detect(url){if(!url)return null;if(cache.has(url))return cache.get(url);try{const res=await fetch(url),ab=await res.arrayBuffer(),ac=new AudioContext(),buf=await ac.decodeAudioData(ab);const rate=buf.sampleRate,channel=buf.getChannelData(0),seconds=Math.min(45,buf.duration),len=Math.floor(seconds*rate),step=Math.max(1,Math.floor(rate/100)),env=[];for(let i=0;i<len;i+=step){let sum=0,end=Math.min(len,i+step);for(let j=i;j<end;j++)sum+=channel[j]*channel[j];env.push(Math.sqrt(sum/Math.max(1,end-i)))}let mean=env.reduce((a,b)=>a+b,0)/Math.max(1,env.length),flux=env.map((v,i)=>i?v-env[i-1]-mean:0).map(v=>Math.max(0,v));const sr=100,minLag=Math.floor(sr*60/180),maxLag=Math.ceil(sr*60/60),corr=[];for(let lag=minLag;lag<=maxLag;lag++){let sum=0;for(let i=lag;i<flux.length;i++)sum+=flux[i]*flux[i-lag];corr.push({lag,score:sum})}corr.sort((a,b)=>b.score-a.score);let lag=corr[0]?.lag;if(!lag){ac.close();return null}let bpm=60*sr/lag;while(bpm<80)bpm*=2;while(bpm>170)bpm/=2;const out=Math.round(bpm*10)/10;cache.set(url,out);ac.close();return out}catch(e){console.warn('BPM detection failed',e);return null}}
async function analyze(audio,k){addReadout(audio,k);const url=audio.currentSrc||audio.src;if(!url||!url.startsWith('blob:'))return;setReadout(k,null);const bpm=await detect(url);bps[k]=bpm;setReadout(k,bpm);if(bpm)window.dispatchEvent(new CustomEvent('cadence:bpm',{detail:{deck:k,bpm}}))}
audioA.addEventListener('loadedmetadata',()=>analyze(audioA,'A'));audioB.addEventListener('loadedmetadata',()=>analyze(audioB,'B'));
if(sync){const old=sync.onclick;sync.onclick=()=>{old?.();setTimeout(()=>{const a=bps.A,b=bps.B;if(a&&b){const targetA=a,targetB=b;audioA.playbackRate=Math.max(.5,Math.min(1.5,targetA/targetB));audioB.playbackRate=1;const status=document.querySelector('#status');if(status)status.textContent=`Beat match ${targetB.toFixed(1)} → ${targetA.toFixed(1)} BPM`; }else{const status=document.querySelector('#status');if(status)status.textContent='BPM not detected; duration match used.'}},0)}}
window.CadenceBPM={get:(k)=>bps[k]||null,analyze};
})();